// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPBTRLo5vSoxnaV2hwqe31m9gqU2LlwjQ',
    appId: '1:271893489797:web:4680aaab52f61c68b821ec',
    messagingSenderId: '271893489797',
    projectId: 'bazario-1',
    authDomain: 'bazario-1.firebaseapp.com',
    storageBucket: 'bazario-1.firebasestorage.app',
    measurementId: 'G-W24G9LSQZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy3etXtphvNYzHG3Xtz6Dnv9fT3HYqvjQ',
    appId: '1:271893489797:android:3248c153ea8eb75eb821ec',
    messagingSenderId: '271893489797',
    projectId: 'bazario-1',
    storageBucket: 'bazario-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JJbBZ7jHg4bfdgkmw-naykI8jQaFqsc',
    appId: '1:271893489797:ios:56c2a78cfcf29c1eb821ec',
    messagingSenderId: '271893489797',
    projectId: 'bazario-1',
    storageBucket: 'bazario-1.firebasestorage.app',
    iosBundleId: 'com.bravocodersunited.bazario.bazario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JJbBZ7jHg4bfdgkmw-naykI8jQaFqsc',
    appId: '1:271893489797:ios:56c2a78cfcf29c1eb821ec',
    messagingSenderId: '271893489797',
    projectId: 'bazario-1',
    storageBucket: 'bazario-1.firebasestorage.app',
    iosBundleId: 'com.bravocodersunited.bazario.bazario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPBTRLo5vSoxnaV2hwqe31m9gqU2LlwjQ',
    appId: '1:271893489797:web:849bced6cde23909b821ec',
    messagingSenderId: '271893489797',
    projectId: 'bazario-1',
    authDomain: 'bazario-1.firebaseapp.com',
    storageBucket: 'bazario-1.firebasestorage.app',
    measurementId: 'G-MT7B4DD4FB',
  );
}
